grpc_server:
  socket_path: /etc/kubeedge/usb.sock
common:
  name: Usb-mapper
  version: v1.13.0
  api_version: v1.0.0
  protocol: camera-usb  # TODO add your protocol name
  address: 127.0.0.1
  edgecore_sock: /etc/kubeedge/dmi.sock
dev_init:
  mode: register

