---
# Source: usb-chart/templates/002-mapper-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usb-dmi-mapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cameraUsbMapper
  template:
    metadata:
      labels:
        app: cameraUsbMapper
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/agent
                    operator: Exists
                  - key: edgeNode
                    operator: In
                    values:
                      - "edge3"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cameraUsbMapper
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: usb-camera-mapper
          image: september9/usb-camera-mapper:v1.2
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ["/kubeedge/main --config-file /kubeedge/config.yaml --v 5"]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /dev
              name: usb-dev
            - name: sock-path
              mountPath: /etc/kubeedge
      volumes:
        - name: sock-path
          hostPath:
            path: /etc/kubeedge
            type: Directory
        - name: usb-dev
          hostPath:
            path: /dev
            type: Directory
      restartPolicy: Always